jj-fzf: rebase: add support for Alt-D to duplicate input
Signed-off-by: Tim Janik <timj@gnu.org>

diff --git a/jj-fzf b/jj-fzf
--- a/jj-fzf
+++ b/jj-fzf
@@ -1199,13 +1199,16 @@ rebasing()
   S="$(xrev "${1:-@}")"
   temp_dir
   echo > $TEMPD/rebasing.env
+  echo 'DP='			>> $TEMPD/rebasing.env
   echo 'FR=--branch'		>> $TEMPD/rebasing.env
   echo 'TO=--destination'	>> $TEMPD/rebasing.env
   echo 'SP=false'		>> $TEMPD/rebasing.env
   echo 'II='			>> $TEMPD/rebasing.env
   export JJFZFONELINE
   PREVIEW=". $TEMPD/rebasing.env"
-  PREVIEW="$PREVIEW"' && echo && echo jj rebase $II $FR '$S' $TO $REV'
+  PREVIEW="$PREVIEW"' && echo'
+  PREVIEW="$PREVIEW"' && { test -z "$DP" || echo jj duplicate '$S' || :; }'
+  PREVIEW="$PREVIEW"' && echo jj rebase $II $FR ${DP:+DUPLICATE-OF-}'${S:0:13}' $TO $REV'
   PREVIEW="$PREVIEW"' && { $SP && echo jj simplify-parents ${FR/-branch/-source} '$S' || :; } && echo'
   PREVIEW="$PREVIEW"' && F=${FR#--} && echo ${F^^}: && $JJFZFONELINE -r '$S' && echo'
   PREVIEW="$PREVIEW"' && T=${TO#--} && echo ${T^^}: && $JJFZFONELINE -r $REV && echo'
@@ -1226,7 +1229,8 @@ rebasing()
 	  --preview "[[ {} =~ $REVPAT ]] || exit; export REV=\"\${BASH_REMATCH[1]}\"; $PREVIEW " \
 	  --prompt "Rebase > " \
 	  --header "$H" --header-first \
-	  --bind "alt-b:execute-silent( gsed 's/^FR=.*/FR=--branch/' -i $TEMPD/rebasing.env )+refresh-preview" \
+	  --bind "alt-d:execute-silent( gsed 's/^DP=..*/DP=x/; s/^DP=$/DP=1/; s/^DP=x.*/DP=/; s/^FR=--branch/FR=--source/' -i $TEMPD/rebasing.env )+refresh-preview" \
+	  --bind "alt-b:execute-silent( gsed 's/^FR=.*/FR=--branch/; s/^DP=.*/DP=/;' -i $TEMPD/rebasing.env )+refresh-preview" \
 	  --bind "alt-s:execute-silent( gsed 's/^FR=.*/FR=--source/' -i $TEMPD/rebasing.env )+refresh-preview" \
 	  --bind "alt-r:execute-silent( gsed 's/^FR=.*/FR=--revisions/' -i $TEMPD/rebasing.env )+refresh-preview" \
 	  --bind "alt-p:execute-silent( gsed 's/^SP=false/SP=x/; s/^SP=true/SP=false/; s/^SP=x/SP=true/' -i $TEMPD/rebasing.env )+refresh-preview" \
@@ -1242,6 +1246,15 @@ rebasing()
   REV="$(rev_changeid "$REV")"
   . $TEMPD/rebasing.env
   rm -f TEMPD/rebasing.env
+  # duplicate input revision
+  test -z "$DP" || {
+    A=( $(rev_children "$S-") ) C=()
+    ( set -x
+      jj duplicate "$S" ) || ERROR
+    B=( $(rev_children "$S-") ) && diff_arrays A B C # find duplicated revision
+    [ ${#C[@]} -eq 1 ] || ERROR "failed to find newly created revision duplicate"
+    S="${C[0]}"
+  }
   # rebase revision
   ( set -x
     jj rebase $II $FR "$S" $TO "$REV"
