jj-fzf: support 'gsed' as GNU sed binary
Signed-off-by: Tim Janik <timj@gnu.org>

diff --git a/jj-fzf b/jj-fzf
--- a/jj-fzf
+++ b/jj-fzf
@@ -52,8 +52,10 @@ fi
 VERSION=0.23.0
 jj --version --ignore-working-copy | grep -Eq 'jj 0\.2[3-9]\.' || die 'jj-0.23 is required'
 fzf --help | grep -Fq ' --header-first' || die 'fzf-0.29 is required'
-sed --version | grep -Fq 'GNU sed' || die 'GNU sed is required'
 awk --version | grep -Fq 'GNU Awk' || die 'GNU Awk is required'
+sed --version | grep -Fq 'GNU sed' &&
+  gsed() { sed "$@"; } && export -f gsed ||
+    gsed --version | grep -Fq 'GNU sed' || die "failed to find 'gsed' in \$PATH (GNU sed)"
 TRACK=--track && FZFHELP="$(fzf --help 2>&1)" && [[ "$FZFHELP" =~ "--track" ]] || TRACK=
 
 # == Early Options ==
@@ -300,7 +302,7 @@ echo_signoff()
   if test "${JJFZF_SIGNOFF:-true}" == true ; then
     echo # separating newline before signoff section
     $JJFZFSHOW -T 'format_detailed_signature(author) ++ "\n"' -r @ |
-      sed -e 's/>.*/>/ ; s/^/Signed-off-by: /'
+      gsed -e 's/>.*/>/ ; s/^/Signed-off-by: /'
   fi
 )
 # Echo current or default message
@@ -316,7 +318,7 @@ echo_commit_msg()
   # start with file name prefixes
   cd "$JJROOT" # create root relative file names
   FILES=()
-  readarray -t FILES < <(jj --ignore-working-copy log --no-graph -r "$R" -T '' -s | sed 's/^\w //')
+  readarray -t FILES < <(jj --ignore-working-copy log --no-graph -r "$R" -T '' -s | gsed 's/^\w //')
   test ${#FILES[@]} -gt 0 &&
     printf "%s: \n" "${FILES[@]}" ||
       echo ""
@@ -568,7 +570,7 @@ file-editor()
   # cd root; otherwise revision file paths will mismatch
   cd "$JJROOT"
   # read files edited by revision
-  readarray -t FILES < <(jj --ignore-working-copy log --no-graph -r "$R" -T '' -s | sed 's/^\w //')
+  readarray -t FILES < <(jj --ignore-working-copy log --no-graph -r "$R" -T '' -s | gsed 's/^\w //')
   # make sure to edit revision
   test "$W" == "$R" || (
     IMMU=$($JJFZFSHOW -r "$R" -T 'if(immutable, "true")')
@@ -594,7 +596,7 @@ help()
   JJCMDS=:
   for w in $( LANG=C
 	      jj --help |
-		sed -r '1,/^Commands:/d; /^\w/{x;q}; s/^ *(\w+)\b.*/\1/' ) ; do
+		gsed -r '1,/^Commands:/d; /^\w/{x;q}; s/^ *(\w+)\b.*/\1/' ) ; do
     [[ $w == help ]] && continue
     JJCMDS="$JJCMDS$w:"
   done
@@ -622,7 +624,7 @@ split-interactive()
 	set -Eeuo pipefail #-x
 	TRUNCATE=y
 	test $TRUNCATE == y && echo -n > "$1" || :
-	sed 's/TRUNCATE=./TRUNCATE=n/' -i "$0"
+	gsed 's/TRUNCATE=./TRUNCATE=n/' -i "$0"
 	__EOF__
   chmod +x $TEMPD/trunc1st.sh
   export EDITOR=$TEMPD/trunc1st.sh
@@ -670,7 +672,7 @@ if [[ $# == 2 ]] && [[ "${1:0:1}" == + ]] ; then
     grep -s -n '' "$file" /dev/null |
     "${FZFPOPUP[@]}" \
       --border-label '-[ LINE HISTORY (EXPERIMENTAL) ]-' --color=border:yellow,label:yellow \
-      --preview " git log --graph --no-patch -M -C --find-copies-harder --pretty='%C(blue)%h %C(yellow)%aL %C(reset)%s%n%b' -L{2}:{1} --color $C | sed 's/Signed-off-by:.*//; /^ *$/d' " \
+      --preview " git log --graph --no-patch -M -C --find-copies-harder --pretty='%C(blue)%h %C(yellow)%aL %C(reset)%s%n%b' -L{2}:{1} --color $C | gsed 's/Signed-off-by:.*//; /^ *$/d' " \
       --bind "enter:execute( git log -M -C --find-copies-harder -L{2},+7:{1} --color $C | $JJFZFPAGER)" \
       --header "File Line History" \
       --no-tac --no-sort +m -d: \
@@ -735,7 +737,7 @@ merging()
 	  --border-label '-[ MERGING ]-' --color=border:bright-blue,label:bright-blue \
 	  --prompt "Merge +> " \
 	  --header "$H" --header-first \
-	  --bind "alt-u:execute-silent( sed 's/0/2/;s/1/0/;s/2/1/' -i $TEMPD/upstream.toggle )+refresh-preview" \
+	  --bind "alt-u:execute-silent( gsed 's/0/2/;s/1/0/;s/2/1/' -i $TEMPD/upstream.toggle )+refresh-preview" \
 	  -m --color=pointer:grey \
 	  --no-tac --no-sort > $TEMPD/selections.txt &&
     mapfile -t selections < $TEMPD/selections.txt &&
@@ -763,8 +765,8 @@ merging()
 	       echo -e "\n* Branch '`rev_bookmark1 $c`' commit log:" ||
 		 echo -e "\n* Branch commit log:" # "$c ^$MERGE_BASE"
 	     git log --pretty=$'\f%s%+b' $c ^$MERGE_BASE |
-	       sed '/^\(Signed-off-by\|Acked-by\|Tested-by\|Cc\):/d' |
-	       sed '/^$/d ; s/^/\t/ ; s/^\t\f$/  (no description)/ ; s/^\t\f/  /'
+	       gsed '/^\(Signed-off-by\|Acked-by\|Tested-by\|Cc\):/d' |
+	       gsed '/^$/d ; s/^/\t/ ; s/^\t\f$/  (no description)/ ; s/^\t\f/  /'
 	   done
 	   echo_signoff
        )
@@ -838,7 +840,7 @@ undone_log()
   # list all oplog descriptions, find description with "undo operation 123abc"
   T='coalesce( self.description().first_line(), " ") ++ "\n"'
   jj --no-pager --ignore-working-copy op log --no-graph --color=never -T "$T" |
-    sed -nr '
+    gsed -nr '
     	# turn "undo operation 123abc" into an exact id with 16 characters
 	/^undo operation [a-f0-9]{16}/s/^undo operation ([a-f0-9]{16}).*/\1/
 	T;	# goto EOS unless the previous s/// matched
@@ -864,12 +866,12 @@ label(if(current_operation, "current_operation"),
 oplog_oneline()
 (
   temp_dir
-  # turn each undone and undo operation on "123abc" into a new sed commands that replaces this operations graph character
+  # turn each undone and undo operation on "123abc" into a new gsed commands that replaces this operations graph character
   undone_log |
-    sed -r 's/([a-f0-9]+)/	s|○(.*\1)|-\\1|		/' > $TEMPD/undone.sed
+    gsed -r 's/([a-f0-9]+)/	s|○(.*\1)|-\\1|		/' > $TEMPD/undone.sed
   # show operation log, filtered through the above sed script to alter markers for undone ops
   jj --no-pager --ignore-working-copy op log --color=always -T "$JJ_FZF_OPLOG_ONELINE" |
-    sed -rf $TEMPD/undone.sed	# beware, script needs to ignore ANSI color escape sequences
+    gsed -rf $TEMPD/undone.sed	# beware, script needs to ignore ANSI color escape sequences
 )
 FUNCTIONS+=( 'oplog_oneline' )
 
@@ -893,8 +895,8 @@ op-log()
     --border-label '-[ OP-LOG ]-' --color=border:bright-yellow,label:bright-yellow \
     --prompt "Operation > " \
     --header "$H" --header-first \
-    --bind "ctrl-d:execute-silent( sed 's/^VIEW=.*/VIEW=diff@oplog/' -i $TEMPD/oplog.env )+refresh-preview" \
-    --bind "ctrl-l:execute-silent( sed 's/^VIEW=.*/VIEW=log@oplog/' -i $TEMPD/oplog.env )+refresh-preview" \
+    --bind "ctrl-d:execute-silent( gsed 's/^VIEW=.*/VIEW=diff@oplog/' -i $TEMPD/oplog.env )+refresh-preview" \
+    --bind "ctrl-l:execute-silent( gsed 's/^VIEW=.*/VIEW=log@oplog/' -i $TEMPD/oplog.env )+refresh-preview" \
     --bind "alt-w:execute-silent( $SELF wdrestore@oplog {} )+abort" \
     --bind "alt-z:execute-silent( $SELF undo-op@oplog {} )+abort" \
     --bind "enter:execute( [[ {} =~ \$OPPAT ]] || exit && export JJFZF_ATOP=\"\${BASH_REMATCH[1]}\" && $SELF logrev @ {q} )" \
@@ -1098,8 +1100,8 @@ reparenting()
       --preview ". $TEMPD/reparenting.env && reparenting_revs {+} && reparenting_cmd" \
       --prompt "Parents > " \
       --header "$H" --header-first \
-      --bind "alt-a:execute-silent( sed 's/^OP=.*/OP=\"|\"/' -i $TEMPD/reparenting.env )+refresh-preview" \
-      --bind "alt-d:execute-silent( sed 's/^OP=.*/OP=\"~\"/' -i $TEMPD/reparenting.env )+refresh-preview" \
+      --bind "alt-a:execute-silent( gsed 's/^OP=.*/OP=\"|\"/' -i $TEMPD/reparenting.env )+refresh-preview" \
+      --bind "alt-d:execute-silent( gsed 's/^OP=.*/OP=\"~\"/' -i $TEMPD/reparenting.env )+refresh-preview" \
       -m --color=pointer:grey \
       --no-tac --no-sort > $TEMPD/selections.txt &&
     mapfile -t selections < $TEMPD/selections.txt &&
@@ -1148,13 +1150,13 @@ rebasing()
 	  --preview "[[ {} =~ $REVPAT ]] || exit; export REV=\"\${BASH_REMATCH[1]}\"; $PREVIEW " \
 	  --prompt "Rebase > " \
 	  --header "$H" --header-first \
-	  --bind "alt-b:execute-silent( sed 's/^FR=.*/FR=--branch/' -i $TEMPD/rebasing.env )+refresh-preview" \
-	  --bind "alt-s:execute-silent( sed 's/^FR=.*/FR=--source/' -i $TEMPD/rebasing.env )+refresh-preview" \
-	  --bind "alt-r:execute-silent( sed 's/^FR=.*/FR=--revisions/' -i $TEMPD/rebasing.env )+refresh-preview" \
-	  --bind "alt-p:execute-silent( sed 's/^SP=false/SP=x/; s/^SP=true/SP=false/; s/^SP=x/SP=true/' -i $TEMPD/rebasing.env )+refresh-preview" \
-	  --bind "ctrl-d:execute-silent( sed 's/^TO=.*/TO=--destination/' -i $TEMPD/rebasing.env )+refresh-preview" \
-	  --bind "ctrl-a:execute-silent( sed 's/^TO=.*/TO=--insert-after/' -i $TEMPD/rebasing.env )+refresh-preview" \
-	  --bind "ctrl-b:execute-silent( sed 's/^TO=.*/TO=--insert-before/' -i $TEMPD/rebasing.env )+refresh-preview" \
+	  --bind "alt-b:execute-silent( gsed 's/^FR=.*/FR=--branch/' -i $TEMPD/rebasing.env )+refresh-preview" \
+	  --bind "alt-s:execute-silent( gsed 's/^FR=.*/FR=--source/' -i $TEMPD/rebasing.env )+refresh-preview" \
+	  --bind "alt-r:execute-silent( gsed 's/^FR=.*/FR=--revisions/' -i $TEMPD/rebasing.env )+refresh-preview" \
+	  --bind "alt-p:execute-silent( gsed 's/^SP=false/SP=x/; s/^SP=true/SP=false/; s/^SP=x/SP=true/' -i $TEMPD/rebasing.env )+refresh-preview" \
+	  --bind "ctrl-d:execute-silent( gsed 's/^TO=.*/TO=--destination/' -i $TEMPD/rebasing.env )+refresh-preview" \
+	  --bind "ctrl-a:execute-silent( gsed 's/^TO=.*/TO=--insert-after/' -i $TEMPD/rebasing.env )+refresh-preview" \
+	  --bind "ctrl-b:execute-silent( gsed 's/^TO=.*/TO=--insert-before/' -i $TEMPD/rebasing.env )+refresh-preview" \
 	  --no-tac --no-sort +m ) &&
     [[ "$REV" =~ $REVPAT ]] &&
     REV="${BASH_REMATCH[1]}" ||
@@ -1331,12 +1333,12 @@ DOC['undo']='Use `jj op undo` to undo the last operation performed by `jj` that 
 undo()
 (
   temp_dir
-  # turn each undone operation "123abc" into an sed delete command
+  # turn each undone operation "123abc" into an gsed delete command
   undone_log |
-    sed -r 's|([a-f0-9]+)|	/\\b\1/d	|' > $TEMPD/delops.sed
+    gsed -r 's|([a-f0-9]+)|	/\\b\1/d	|' > $TEMPD/delops.sed
   # list operation IDs, skipping undone ones
   jj --ignore-working-copy op log --no-graph -T 'self.id().short(16) ++ " " ++ self.description().first_line() ++ "\n"' |
-    sed -rf $TEMPD/delops.sed > $TEMPD/undoable-ops.lst
+    gsed -rf $TEMPD/delops.sed > $TEMPD/undoable-ops.lst
   # fetch first
   read op rest < $TEMPD/undoable-ops.lst
   # read -p "Undo $op? " YN ; [[ "${YN:0:1}" =~ [yY] ]] || exit
@@ -1376,7 +1378,7 @@ if [[ "${1:-}" = --help ]] ; then
       echo "*$k:* **$NAME**"
       D="${DOC[$NAME]:-}"
       test -z "$D" ||
-	echo "$D" | fold -s -w78 | sed 's/^/  /'
+	echo "$D" | fold -s -w78 | gsed 's/^/  /'
     done
   ) | (
     B=$'\e[1m'              # Bold
@@ -1399,7 +1401,7 @@ if [[ "${1:-}" = --help ]] ; then
     s,(\bhttps?://[^ ()\r]+),$U\1$Z,g               # Link
     "
     tr \\n \\r |
-      { $COLOR && sed -re "$SEDSCRIPT" || cat ; } |
+      { $COLOR && gsed -re "$SEDSCRIPT" || cat ; } |
       tr \\r \\n
   )
   exit 0
